on:
  push:
    branches:
      - main
name: backend-deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_URL_PATH_PREFIX: ${{secrets.URL_PATH_PREFIX}}
          envkey_PORT: ${{secrets.PORT}}
          file_name: .env
          fail_on_empty: true

      - name: Run
        run: docker compose up --build -d
